### ISSUE TITLE
Please pre-compile bundle for use in Create-A-React apps

### ISSUE THREAD

**Issue by surbas** [mozilla-rpweb/react-lazylog#4]
First awesome log viewer. It was a breeze to setup, but when I went to build my app I got a message in my console cause, CAR was unable to uglify this library. I got a link to the following
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Would it be possible to have pre-compiled 'binaries' sent when you guys put this on npm?

I hacked together a fork that used webpack directly, if it helps, but I am afraid it too messy to even deem worthy of a proper pull. 
https://github.com/surbas/react-lazylog

**Comment by eliperelman** [comment]
So the reason this doesn't work directly in Create React App is I don't think CRA does minification on the node_modules directory. Since there is ES2015+ code in the this package, and Uglify only works with ES5 code, that's where the problem lies.

As mentioned in the README:

> Works in latest browser versions, including iOS Safari and Android Chrome

So the repo is compiled using babel-preset-env to support the latest browser versions and minified using Babel minify, but it seems that through the use of Uglify in CRA it wants code compiled for more browsers than this project supports.

As an alternative, you could fork and then do a configuration override to compile to different ES targets.

**Comment by eliperelman** [comment]
Hey @surbas, turns out it was simple enough to compile two versions! I've released v2 which allows you to import an ES5 version for CRA:

```js
import LazyLog from 'react-lazylog/lib/LazyLog.es5';
```

Lemme know how that works!

**Comment by surbas** [comment]
Works great! Thanks.

**Comment by ebuildy** [comment]
with latest version:

    import { LazyLog } from  'react-lazylog/es5';
